In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("Data.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [4]:
data.shape

(10, 4)

In [5]:
data.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [6]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [7]:
data["Age"]

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [8]:
data.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [9]:
data[["Age","Salary"]]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [10]:
x=data.iloc[:,:-1]

In [11]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [12]:
y=data.iloc[:,-1]

In [13]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [14]:
x["Salary"]=x["Salary"].fillna(x["Salary"].mean())

In [15]:
x

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778
5   France  35.0  58000.000000
6    Spain   NaN  52000.000000
7   France  48.0  79000.000000
8  Germany  50.0  83000.000000
9   France  37.0  67000.000000

In [16]:
x["Age"]=x["Age"].fillna(int(x["Age"].mean()))

In [17]:
x

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778
5   France  35.0  58000.000000
6    Spain  38.0  52000.000000
7   France  48.0  79000.000000
8  Germany  50.0  83000.000000
9   France  37.0  67000.000000

In [18]:
x.fillna({"Age":x["Age"].mean(),"Salary":x["Salary"].mean()},inplace=True)
x

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778
5   France  35.0  58000.000000
6    Spain  38.0  52000.000000
7   France  48.0  79000.000000
8  Germany  50.0  83000.000000
9   France  37.0  67000.000000

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
columnTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [21]:
x2 = columnTransformer.fit_transform(x)

In [22]:
x2=x2[:,1:]

In [23]:
x2

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [24]:
x3=pd.get_dummies(x, drop_first=True)

In [25]:
x3

Age        Salary  Country_Germany  Country_Spain
0  44.0  72000.000000                0              0
1  27.0  48000.000000                0              1
2  30.0  54000.000000                1              0
3  38.0  61000.000000                0              1
4  40.0  63777.777778                1              0
5  35.0  58000.000000                0              0
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
8  50.0  83000.000000                1              0
9  37.0  67000.000000                0              0

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le = LabelEncoder()
y= le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test=train_test_split(x3,y,random_state=0,train_size=0.8,test_size=0.2)

In [30]:
x_train

Age        Salary  Country_Germany  Country_Spain
4  40.0  63777.777778                1              0
9  37.0  67000.000000                0              0
1  27.0  48000.000000                0              1
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
3  38.0  61000.000000                0              1
0  44.0  72000.000000                0              0
5  35.0  58000.000000                0              0

In [31]:
x_test

Age   Salary  Country_Germany  Country_Spain
2  30.0  54000.0                1              0
8  50.0  83000.0                1              0

In [32]:
y_train


array([1, 1, 1, 0, 1, 0, 0, 1])

In [33]:
y_test

array([0, 0])

In [34]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler = MinMaxScaler()
scaler.fit(x_train)
scaled = scaler.transform(x_train)
scaled

array([[0.61904762, 0.50896057, 1.        , 0.        ],
       [0.47619048, 0.61290323, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.52380952, 0.12903226, 0.        , 1.        ],
       [1.        , 1.        , 0.        , 0.        ],
       [0.52380952, 0.41935484, 0.        , 1.        ],
       [0.80952381, 0.77419355, 0.        , 0.        ],
       [0.38095238, 0.32258065, 0.        , 0.        ]])

In [36]:
scaler1=MinMaxScaler()
scaler1.fit(x_test)
scaled1=scaler.transform(x_test)
scaled1

array([[0.14285714, 0.19354839, 1.        , 0.        ],
       [1.0952381 , 1.12903226, 1.        , 0.        ]])

In [37]:
a=StandardScaler().fit(x_train[["Salary","Age"]])
c=a.transform(x_train[["Salary","Age"]])
c

array([[ 0.12381479,  0.27978024],
       [ 0.46175632, -0.23673712],
       [-1.53093341, -1.95846165],
       [-1.11141978, -0.06456467],
       [ 1.7202972 ,  1.65715986],
       [-0.16751412, -0.06456467],
       [ 0.98614835,  0.96847005],
       [-0.48214934, -0.58108203]])

In [1]:
from sklearn.metrics import r2_score